apiVersion: v1
kind: Service
metadata:
  name: chaos-target-service
  labels:
    app: chaos-target-app
spec:
  selector:
    app: chaos-target-app
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
