apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: network-latency-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=chaos-target-app'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  engineState: 'active'
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: network-latency
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '90' # Run for 90 seconds
            # Network parameters
            - name: NETWORK_LATENCY
              value: '50' # 50 millisecond delay
            - name: JITTER
              value: '0' # No random variation
            - name: PODS_AFFECTED_PERC
              value: '33' # Target 1 of 3 replicas
            # Target all traffic
            - name: DESTINATION_PORTS
              value: '80'
  # Automated Validation Probes
  probe:
    - name: check-availability-with-latency
      type: httpProbe
      mode: Continuous
      httpProbe/inputs:
        url: http://chaos-target-service.default.svc.cluster.local:80
        method:
          get:
            criteria: ==
            responseCode: "200"
      # The probe timeout is slightly increased (8s) to account for the injected 50ms latency.
      runProperties:
        probeTimeout: 8
        interval: 5
        retry: 3